# Generated by Django 5.2.7 on 2026-04-14 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('exam', 'Exam'), ('test', 'Test'), ('quiz', 'Quiz'), ('presentation', 'Presentation'), ('project', 'Project')], default='exam', max_length=20)),
                ('date', models.DateTimeField()),
                ('weight', models.PositiveIntegerField(default=0)),
                ('prep_status', models.CharField(choices=[('not-started', 'Not Started'), ('started', 'Started'), ('prepared', 'Prepared'), ('ready', 'Ready')], default='not-started', max_length=20)),
                ('estimated_study_hours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('passing_score', models.PositiveIntegerField(blank=True, null=True)),
                ('current_score', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentPreparationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_level', models.PositiveIntegerField(default=1)),
                ('readiness_notes', models.TextField(blank=True)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_status', to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_topics', to='assessments.assessment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_topics', to='academics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assessment', 'topic')},
            },
        ),
    ]
